#!/usr/bin/python3
from flask import redirect
from flask import send_from_directory
from models.student import Student
from website.routes import app_routes
from website.routes import session
from routes import default_img, default_name

@app_routes.route('/profileImage', methods=['GET'], strict_slashes=False)
def download_image():
    """Download student profile image"""

    if 'id' in session:
        student = storage.get(Student, session['id'])

        if student.profile_pic:
            path = student.profile_pic.img
            filename = student.profile_pic.name
        else:
            path = default_image
            name = default_name

        return send_from_directory(path, filename)

    return redirect(url_for('login'))
